# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    env:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push Folder
        uses: dmnemec/copy_file_to_another_repo_action@main
        with:
          source_file: 'move-directory/'
          destination_repo: 'nvelinz/github-action-push-output'
          destination_folder: 'docs/copied-file'
          user_email: 'nicolai.velzel@gmail.com'
          user_name: 'nvelinz'
          commit_message: 'Add folder from Repository'

#      - name: Push Folder
#        uses: dmnemec/copy_file_to_another_repo_action@main
#        with:
#          source_file: 'move-directory/'
#          destination_repo: 'bcc-code/bcc-code.github.io'
#          destination_folder: 'docs/copied-file'
#          user_email: 'nicolai.velzel@gmail.com'
#          user_name: 'nvelinz'
#          commit_message: 'Add folder from Repository'    